begin;
insert into auth.users(id) values ('10000000-0000-4000-8000-000000000001'),('10000000-0000-4000-8000-000000000002');
insert into businesses(id,owner_id,name) values ('20000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','Finance test');
insert into business_members(business_id,user_id) values ('20000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001');
insert into customers(id,business_id,name,phone) values ('30000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','Test','2025550100');
set local role authenticated;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
do $$
declare j jobs; j2 jobs; inv invoices; again invoices; e estimates; result jsonb; items jsonb:='[{"description":"Service","quantity":1,"unitPrice":100,"type":"service"}]'; pid uuid:=gen_random_uuid(); bid uuid:='20000000-0000-4000-8000-000000000001'; cid uuid:='30000000-0000-4000-8000-000000000001';
begin
 if private.document_total('[{"description":"Round","quantity":0.5,"unitPrice":0.01,"type":"service"},{"description":"Round","quantity":1.005,"unitPrice":1,"type":"service"}]')<>1.02 then raise exception 'Rounding failed'; end if;
 begin perform private.document_total('[]'); raise exception 'Empty accepted'; exception when invalid_parameter_value then null; end;
 begin perform private.document_total('[{"description":"Bad","quantity":0,"unitPrice":1,"type":"service"}]'); raise exception 'Zero accepted'; exception when invalid_parameter_value then null; end;
 insert into jobs(business_id,customer_id,title,price) values(bid,cid,'Priced job',125.50) returning * into j;
 select * into inv from convert_job_to_invoice(j.id);
 select * into again from convert_job_to_invoice(j.id);
 if inv.total<>125.50 or inv.id<>again.id or (select count(*) from invoices where job_id=j.id)<>1 then raise exception 'Job conversion failed'; end if;
 insert into jobs(business_id,customer_id,title) values(bid,cid,'Unpriced') returning * into j2;
 begin perform convert_job_to_invoice(j2.id); raise exception 'Unpriced accepted'; exception when raise_exception then if sqlerrm='Unpriced accepted' then raise; end if; end;
 if exists(select 1 from invoices where job_id=j2.id) then raise exception 'Unpriced invoice created'; end if;
 select * into e from create_job_estimate(j2.id,items,null,'lawn','none',3);
 if (select id from create_job_estimate(j2.id,items,null,'lawn','none',3))<>e.id then raise exception 'Estimate duplicated'; end if;
 update estimates set status='approved' where id=e.id;
 if (select id from convert_estimate_to_job(e.id))<>j2.id then raise exception 'Job link lost'; end if;
 insert into estimates(business_id,customer_id,status,line_items,total) values(bid,cid,'approved',items,999) returning * into e;
 if e.total<>100 then raise exception 'Client total trusted'; end if;
 select * into j from convert_estimate_to_job(e.id);
 if j.status<>'draft' or j.scheduled_date is not null or (select id from convert_estimate_to_job(e.id))<>j.id then raise exception 'Estimate conversion failed'; end if;
 select * into inv from convert_job_to_invoice(j.id);
 if inv.total<>100 or inv.estimate_id<>e.id then raise exception 'Estimate charges lost'; end if;
 begin update invoices set status='paid' where id=inv.id; raise exception 'Unrecorded paid accepted'; exception when check_violation then null; end;
 result:=record_invoice_payment(inv.id,pid,40,'cash','private note');
 if (result->'invoice'->>'paid_total')::numeric<>40 or result->'invoice'->>'status'<>'sent' then raise exception 'Partial failed'; end if;
 perform record_invoice_payment(inv.id,pid,40,'cash','private note');
 if (select count(*) from invoice_payments where invoice_id=inv.id)<>1 then raise exception 'Retry duplicated payment'; end if;
 begin perform record_invoice_payment(inv.id,pid,41,'cash','private note'); raise exception 'Changed retry accepted'; exception when check_violation then null; end;
 begin perform record_invoice_payment(inv.id,gen_random_uuid(),61,'cash'); raise exception 'Overpay accepted'; exception when check_violation then null; end;
 begin perform record_invoice_payment(inv.id,gen_random_uuid(),0.001,'cash'); raise exception 'Precision accepted'; exception when invalid_parameter_value then null; end;
 begin update invoice_payments set amount=1 where id=pid; raise exception 'Ledger edit accepted'; exception when check_violation then null; end;
 begin delete from invoice_payments where id=pid; raise exception 'Ledger delete accepted'; exception when check_violation then null; end;
 begin update invoices set line_items='[{"description":"Low","quantity":1,"unitPrice":20,"type":"service"}]' where id=inv.id; raise exception 'Underpaid edit accepted'; exception when check_violation then null; end;
 update invoices set paid_total=999 where id=inv.id;
 if (select paid_total from invoices where id=inv.id)<>40 then raise exception 'Cached balance trusted'; end if;
 result:=get_portal_data(cid);
 if (result->'invoices'->0->>'balance_due')::numeric<>60 or result::text like '%private note%' then raise exception 'Portal partial balance/privacy failed'; end if;
 pid:=gen_random_uuid();
 result:=record_invoice_payment(inv.id,pid,60,'check');
 perform record_invoice_payment(inv.id,pid,60,'check');
 if result->'invoice'->>'status'<>'paid' or (result->'invoice'->>'paid_total')::numeric<>100 then raise exception 'Full payment failed'; end if;
 begin update invoices set status='voided' where id=inv.id; raise exception 'Paid void accepted'; exception when check_violation then null; end;
 perform set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000002',true);
 if get_portal_data(cid) is not null then raise exception 'Foreign portal exposed'; end if;
 begin perform record_invoice_payment(inv.id,gen_random_uuid(),1,'cash'); raise exception 'Foreign payment accepted'; exception when insufficient_privilege then null; end;
 begin perform convert_job_to_invoice(j.id); raise exception 'Foreign conversion accepted'; exception when insufficient_privilege then null; end;
 if has_function_privilege('anon','public.record_invoice_payment(uuid,uuid,numeric,text,text)','execute') then raise exception 'Anonymous payment privilege'; end if;
end $$;
rollback;
