begin;
insert into auth.users(id) values ('10000000-0000-4000-8000-000000000001');
insert into businesses(id,owner_id,name) values ('20000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','Scheduling test');
insert into business_members(business_id,user_id) values ('20000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001');
insert into customers(id,business_id,name,phone) values ('30000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','Test','2025550100');
set local role authenticated;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
do $$
declare j jobs; successor jobs; third jobs; req uuid; bid uuid:='20000000-0000-4000-8000-000000000001'; cid uuid:='30000000-0000-4000-8000-000000000001';
begin
 insert into jobs(business_id,customer_id,title,status,scheduled_date,scheduled_time,recurring,price,checklist) values(bid,cid,'Monthly','scheduled','2028-01-31','09:30','monthly',75,'[{"id":"old","text":"Inspect","done":true}]') returning * into j;
 update jobs set status='complete' where id=j.id;
 select * into successor from jobs where recurring_parent_id=j.id;
 if successor.scheduled_date<>'2028-02-29' or successor.price<>75 or successor.checklist->0->>'done'<>'false' or successor.invoice_id is not null or successor.estimate_id is not null then raise exception 'Monthly rollover or carry-forward failed'; end if;
 update jobs set status='complete' where id=j.id;
 update jobs set status='in-progress' where id=j.id;
 update jobs set status='complete' where id=j.id;
 if (select count(*) from jobs where recurring_parent_id=j.id)<>1 then raise exception 'Duplicate recurrence'; end if;
 update jobs set status='complete' where id=successor.id;
 select * into third from jobs where recurring_parent_id=successor.id;
 if third.scheduled_date<>'2028-03-31' then raise exception 'Anchor drift'; end if;
 if (select completed_at from jobs where id=j.id) is null then raise exception 'No completion time'; end if;
 if exists(select 1 from jsonb_array_elements(get_portal_data(cid)->'jobs') x where x->>'id'=j.id::text and x->>'status'<>'complete') then raise exception 'Portal completion not reflected'; end if;
 insert into jobs(business_id,customer_id,title,status,scheduled_date,recurring) values(bid,cid,'Weekly','scheduled','2028-12-28','weekly') returning * into j;
 update jobs set status='complete' where id=j.id;
 if (select scheduled_date from jobs where recurring_parent_id=j.id)<>'2029-01-04' then raise exception 'Year rollover'; end if;
 insert into job_schedule_requests(business_id,customer_id,job_id,request_type,requested_date,status) values(bid,cid,third.id,'reschedule','2028-04-02','pending') returning id into req;
 update job_schedule_requests set status='approved' where id=req;
 if (select scheduled_date from jobs where id=third.id)<>'2028-04-02' then raise exception 'Approval did not reschedule'; end if;
 insert into job_schedule_requests(business_id,customer_id,job_id,request_type,status) values(bid,cid,third.id,'cancel','pending') returning id into req;
 update job_schedule_requests set status='approved' where id=req;
 if (select status from jobs where id=third.id)<>'cancelled' then raise exception 'Approval did not cancel'; end if;
 if exists(select 1 from jobs where recurring_parent_id=third.id) then raise exception 'Cancel generated visit'; end if;
 insert into job_schedule_requests(business_id,customer_id,job_id,request_type,requested_date,status) values(bid,cid,third.id,'reschedule','2028-04-03','pending') returning id into req;
 begin update job_schedule_requests set status='approved' where id=req; raise exception 'Closed job approved'; exception when check_violation then null; end;
 if (select status from job_schedule_requests where id=req)<>'pending' then raise exception 'Failed approval not rolled back'; end if;
 begin insert into jobs(business_id,customer_id,title,status,scheduled_time) values(bid,cid,'Bad','draft','09:00'); raise exception 'Time without date accepted'; exception when check_violation then null; end;
 begin update jobs set duration_minutes=0 where id=third.id; raise exception 'Bad duration accepted'; exception when check_violation then null; end;
end $$;
rollback;
