import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { createHandler } from '../../functions/send-email/handler.ts';
import { buildMessage, validEmail } from '../../functions/send-email/message.ts';
const id='11111111-1111-4111-8111-111111111111', actor='22222222-2222-4222-8222-222222222222', bid='33333333-3333-4333-8333-333333333333';
const doc={id,kind:'invoice',business_name:'A <B>',customer_name:'<img onerror=evil>',line_items:[{description:'<script>x</script>',quantity:1,unitPrice:10}],total:10,paid_total:3,balance_due:7,contact_email:'reply@example.com',notes:'<b>note</b>'};
assert(!buildMessage(doc).html.includes('<script>'));
assert(buildMessage(doc).html.includes('&lt;img'));
assert(buildMessage(doc).subject.includes('$7.00'));
assert(!validEmail('x@example.com\r\nBcc:y@example.com'));
let requests=0,updates=[],enabled=true,member=true,authenticated=true,claimed=true,state='processing',provider='accepted',status='sent';
const chain=data=>({select(){return this},eq(){return this},single:async()=>({data}),maybeSingle:async()=>({data})});
const client={auth:{getUser:async()=>({data:{user:authenticated?{id:actor}:null}})},from:table=>chain(table==='invoices'?{business_id:bid,customer_id:id,status}:table==='business_members'?(member?{business_id:bid}:null):{email:'customer@example.com'}),rpc:async()=>({data:doc})};
const admin={rpc:async()=>({data:{id,claimed,status:state,recipient:'customer@example.com',provider_id:'provider-id'}}),from:()=>({update(value){updates.push(value);return {eq:async()=>({error:null})}}})};
const handler=createHandler({client:()=>client,admin:()=>admin,env:key=>({CUSTOMER_EMAIL_ENABLED:enabled?'true':'false',CUSTOMER_EMAIL_FROM:'sender@example.com',RESEND_API_KEY:'test-only'})[key],fetch:async()=>{requests++;if(provider==='timeout')throw Error('timeout');return new Response(JSON.stringify(provider==='accepted'?{id:'provider-id'}:{error:'bad'}),{status:provider==='accepted'?200:422});}});
const request=body=>handler(new Request('http://test',{method:'POST',headers:{Authorization:'Bearer local-test'},body:JSON.stringify(body??{type:'invoice',recordId:id,requestId:id})}));
authenticated=false;assert.equal((await request()).status,401);authenticated=true;
member=false;assert.equal((await request()).status,403);member=true;
assert.equal((await request({type:'invoice',recordId:id,requestId:id,to:'attacker@example.com'})).status,400);
enabled=false;assert.equal((await request()).status,503);assert.equal((await (await request({type:'invoice',recordId:id,action:'status'})).json()).ready,false);enabled=true;
status='draft';assert.equal((await request()).status,422);status='sent';assert.equal(requests,0);
assert.equal((await request()).status,200);assert.equal(updates.at(-1).status,'accepted');
claimed=false;state='accepted';assert.equal((await request()).status,200);assert.equal(requests,1);
state='processing';assert.equal((await request()).status,409);assert.equal(requests,1);
claimed=true;provider='timeout';assert.equal((await request()).status,502);assert.equal(updates.at(-1).status,'unknown');
provider='rejected';assert.equal((await request()).status,502);assert.equal(updates.at(-1).status,'failed');
console.log('PASS email handler: authentication, staff authorization, injected recipient, disabled sender, drafts, acceptance, duplicate requests, uncertain and rejected outcomes, escaped templates.');
const db=new PGlite();
try {
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;
create table businesses(id uuid primary key);create table business_members(business_id uuid,user_id uuid);grant select on business_members to authenticated;
create table invoices(id uuid primary key,business_id uuid,customer_id uuid,status text);create table estimates(like invoices including all);create table customers(id uuid primary key,business_id uuid,email text);
insert into businesses values('${bid}');insert into business_members values('${bid}','${actor}');insert into customers values('${id}','${bid}','customer@example.com');insert into invoices values('${id}','${bid}','${id}','sent');`);
await db.exec(readFileSync(new URL('../../migrations/20260926180159_customer_email_delivery.sql',import.meta.url),'utf8'));
const call=`select claim_customer_email('${id}','${actor}','invoice','${id}','customer@example.com') as attempt`;
await db.exec('set role authenticated');await assert.rejects(db.query(call),/permission denied/);await db.exec('reset role');
await db.exec('set role service_role');let r=await db.query(call);assert.equal(r.rows[0].attempt.claimed,true);r=await db.query(call);assert.equal(r.rows[0].attempt.claimed,false);
await assert.rejects(db.query(`select claim_customer_email('44444444-4444-4444-8444-444444444444','${actor}','invoice','${id}','customer@example.com')`),/outcome checked/);
await assert.rejects(db.query(`select claim_customer_email('${id}','44444444-4444-4444-8444-444444444444','invoice','${id}','customer@example.com')`),/unavailable/);
await db.exec(`reset role;update customer_email_deliveries set status='accepted';set role service_role;`);
await assert.rejects(db.query(`select claim_customer_email('44444444-4444-4444-8444-444444444444','${actor}','invoice','${id}','customer@example.com')`),/rate limit/);
await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','44444444-4444-4444-8444-444444444444',false);`);assert.equal((await db.query('select * from customer_email_deliveries')).rows.length,0);
await db.exec(`select set_config('request.jwt.claim.sub','${actor}',false)`);assert.equal((await db.query('select * from customer_email_deliveries')).rows.length,1);
await assert.rejects(db.query(`update customer_email_deliveries set status='accepted'`),/permission denied/);
console.log('PASS email SQL: service-only writes, staff history isolation, duplicate claims and rate limits.');
} finally {await db.close();}
