import assert from 'node:assert/strict';
import {suggestRoute,navigationLink,distanceKm} from '../../../src/lib/employeeRouting.ts';
import {foregroundLocation} from '../../../src/lib/foregroundLocation.ts';
const stop=(id,longitude,time=null)=>({id,title:id,status:'scheduled',latitude:0,longitude,scheduled_time:time});
const jobs=[stop('far',10),stop('near',1),stop('appointment',4,'09:00'),{...stop('unknown',0),latitude:null},{...stop('closed',2),status:'complete'}];
assert.deepEqual(suggestRoute(jobs,{latitude:0,longitude:0}).map(j=>j.id),['appointment','near','far','unknown']);
assert.deepEqual(suggestRoute([stop('far',10),stop('near',1)],{latitude:0,longitude:0}).map(j=>j.id),['near','far']);
assert.equal(distanceKm({latitude:0,longitude:0},{latitude:0,longitude:0}),0);
assert.equal(navigationLink({...stop('unknown',0),latitude:null,address:''}),null);
assert.ok(navigationLink(stop('near',1)).includes('0%2C1'));
let callback,visible=true,time=100000,cleared=false,sends=0;
const tracker=foregroundLocation({visible:()=>visible,now:()=>time,watch:ok=>{callback=ok;return 12;},clear:id=>{assert.equal(id,12);cleared=true;},send:async()=>{sends++;},onError:()=>assert.fail('Unexpected error')});
tracker.start();
const fix=()=>({timestamp:time,coords:{latitude:0,longitude:0,accuracy:5}});
await callback(fix());assert.equal(sends,1);
await callback(fix());assert.equal(sends,1);
time+=15000;await callback(fix());assert.equal(sends,2);
time+=15000;visible=false;await callback(fix());assert.equal(sends,2);
visible=true;await callback({...fix(),timestamp:time-31000});assert.equal(sends,2);
tracker.stop();await callback(fix());assert.equal(sends,2);assert.equal(cleared,true);
let denied='';const deniedTracker=foregroundLocation({visible:()=>true,watch:(_ok,fail)=>{fail({code:1,message:'Denied'});return 1;},clear:()=>{},send:async()=>assert.fail(),onError:m=>{denied=m;}});deniedTracker.start();assert.match(denied,/permission was denied/);deniedTracker.stop();
console.log('PASS: route ordering and foreground-location throttling, stale fixes, hidden app, stop and permission denial. No device location accessed.');
